
version: "3.8"

services:
    nodered:
        image: nodered/node-red
        container_name: nodered_testing
        volumes:
          - ./debug/:/data
        ports:
          - "1880:1880"
        privileged: true